const express = require('express')
const router = express.Router()
const updateController = require('../controllers/update')

router.get('/specials', updateController.getSpecials)
router.get('/archives', updateController.getArchives)
router.get('/createMenuItem', updateController.createMenuItem)
router.get('/desserts', updateController.getDesserts)
router.get('/appetizers', updateController.getAppetizers)
router.get('/beer', updateController.getBeer)
router.get('/btg', updateController.getBTG)
router.get('/cavaChampagne', updateController.getCavaChampagne)
router.get('/charcuterie', updateController.getCharcuterie)
router.get('/craftDrinks', updateController.getCraftDrinks)
router.get('/entrees', updateController.getEntrees)
router.get('/nonAlcoholic', updateController.getNonAlcoholic)
router.get('/redFrance', updateController.getRedFrance)
router.get('/redItaly', updateController.getRedItaly)
router.get('/redSpain', updateController.getRedSpain)
router.get('/rose', updateController.getRose)
router.get('/sangria', updateController.getSangria)
router.get('/sides', updateController.getSides)
router.get('/whiteFrance', updateController.getWhiteFrance)
router.get('/whiteGermany', updateController.getWhiteGermany)
router.get('/whiteItaly', updateController.getWhiteItaly)
router.get('/whiteSpain', updateController.getWhiteSpain)
router.get('/menuItem', updateController.getUpdateMenuItem)

module.exports = router